### ISSUE TITLE
Changing a Route in Disraptor: Do not show the blank page?

### ISSUE THREAD

**Issue by mam10eks** [disraptor/disraptor#12]
When a user follows a link in disraptor, the current behaviour is: 
1. The user clicks the link (or the page is refreshed, e.g. when a software is running in TIRA)
2. The page becomes blank immediately
3. The page remains blank until the new route is successfully loaded

This behaviour annoys me on various locations on TIRA (where some pages need a serious time to load).
E.g. the user sees blank pages for a very long time (especially when you run a software, you usually only see blank pages)

I would prefer a different approach:
1. The user clicks the link (or the page is refreshed, e.g. when a software is running in TIRA)
2. The user sees a "loading indicator" (maybe the current wheel over the page, maybe a progress bar at the top) that shows that something is happening, besides that, the current page remains as it is
3. When the new page is loaded, it replaces the old one, the loading indicator is removed

**Comment by mam10eks** [comment]
@BastianGrahm @potthast What do you think? I think this should be easy, and I think it would improve the useability.

**Comment by BastianGrahm** [comment]
I don't think this is happening anymore. Also if I recall and understand correctly this behavior is hard to change, since it's not Disraptor controlling when the page is "unloaded" and replaced but Discourse (or rather Ember).

I will be closing this for now but keep it in the back of my head if something irritating like this comes up again.
